ALTER TABLE `x5t20wxo8nmqqxfz`.`city_attributes` 
CHANGE COLUMN `LosAngeles` `Los Angeles` TEXT NULL DEFAULT NULL ,
CHANGE COLUMN `SanDiego` `San Diego` TEXT NULL DEFAULT NULL ,
CHANGE COLUMN `SanFrancisco` `San Francisco` TEXT NULL DEFAULT NULL ,
CHANGE COLUMN `LasVegas` `Las Vegas` TEXT NULL DEFAULT NULL ,
CHANGE COLUMN `SanAntonio` `San Antonio` TEXT NULL DEFAULT NULL ,
CHANGE COLUMN `Kansas City` `KansasCity` TEXT NULL DEFAULT NULL ,
CHANGE COLUMN `Saint Louis` `SaintLouis` TEXT NULL DEFAULT NULL ,
CHANGE COLUMN `New York` `NewYork` TEXT NULL DEFAULT NULL ,
CHANGE COLUMN `Tel Aviv District` `TelAviv` TEXT NULL DEFAULT NULL ;